// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMPGeiV6iTE1SUo59CNeZq-jcydOh0cO0',
    appId: '1:81327344295:web:ca0168b54399ab4303a982',
    messagingSenderId: '81327344295',
    projectId: 'smarttasks-4a426',
    authDomain: 'smarttasks-4a426.firebaseapp.com',
    storageBucket: 'smarttasks-4a426.firebasestorage.app',
    measurementId: 'G-5BVWZ650NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxSywsrWplH0kC6tN95kv10uyo-_hUBE',
    appId: '1:81327344295:android:9c977ab8ce0b9d5803a982',
    messagingSenderId: '81327344295',
    projectId: 'smarttasks-4a426',
    storageBucket: 'smarttasks-4a426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9VMV2iGbVGOytjBPEgb52VP7tl4rnRvs',
    appId: '1:81327344295:ios:853606a7d78752ef03a982',
    messagingSenderId: '81327344295',
    projectId: 'smarttasks-4a426',
    storageBucket: 'smarttasks-4a426.firebasestorage.app',
    iosBundleId: 'com.example.thuchanh06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9VMV2iGbVGOytjBPEgb52VP7tl4rnRvs',
    appId: '1:81327344295:ios:853606a7d78752ef03a982',
    messagingSenderId: '81327344295',
    projectId: 'smarttasks-4a426',
    storageBucket: 'smarttasks-4a426.firebasestorage.app',
    iosBundleId: 'com.example.thuchanh06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMPGeiV6iTE1SUo59CNeZq-jcydOh0cO0',
    appId: '1:81327344295:web:b61cbb64930e653d03a982',
    messagingSenderId: '81327344295',
    projectId: 'smarttasks-4a426',
    authDomain: 'smarttasks-4a426.firebaseapp.com',
    storageBucket: 'smarttasks-4a426.firebasestorage.app',
    measurementId: 'G-V1HBC6NCLY',
  );
}
